import { calculateTimeDifferences } from '@/frontend/utils/time'
import moment from 'moment'
import { useState } from 'react'
import { useForm } from 'react-hook-form'
import Markdown from 'react-markdown'
import rehypeRaw from 'rehype-raw'
import Program from './Program'

const MIALogs = () => {
    const [MIAlogs, setMIALogs] = useState(null)
    const [showProgramsList, setShowProgramsList] = useState(false)
    const [showResponse, setShowResponse] = useState(false)

    const {
        register,
        handleSubmit
        // formState: { errors }
    } = useForm()

    const getLogs = async (formData) => {
        if (formData.day.length < 2) formData.day = '0' + formData.day
        if (formData.month.length < 2) formData.month = '0' + formData.month

        const params = new URLSearchParams(formData)
        const result = await fetch('/api/logs?' + params.toString())
        const data = await result.json()
        const updateDates = data.logs.map(data => {
            const dateUpdated = data.date ? new Date(data.date.replace('Z', '-05:00')) : ''
            data.date = dateUpdated
            const times = calculateTimeDifferences(data.times)
            data.times = times

            return data
        })
        const sortedDates = updateDates.sort((dateA, dateB) => dateA.date - dateB.date)

        setMIALogs(sortedDates.reverse() ?? [])
    }

    return <>
        <h3>MIA Logs</h3>
        <p className="description">
            In this section, you can view logs generated by MIA. You can filter by date and time.
        </p>
        <form onSubmit={handleSubmit(getLogs)}>
            <div className="wrapper-date-inputs">
                <input type="text" {...register('day', {
                    value: new Date().getDate().toString()
                })} />
                -
                <input type="text" {...register('month', {
                    value: new Date().getMonth() + 1 + ''
                })} />
                -
                <input type="text" {...register('year', {
                    value: new Date().getFullYear().toString()
                })} />
            </div>
            <div className="wrapper-hour-inputs">
                <input type="time" {...register('start', {
                    value: '00:00'
                })}/>
                -
                <input type="time" {...register('end', {
                    value: '23:59'
                })}/>
            </div>
            <button className="btn-view-logs" type="submit">View Logs</button>
        </form>
        {
            MIAlogs && (MIAlogs.length > 0
                ? <p >
                    Showing
                    <span className="number-logs">
                        {MIAlogs.length}
                    </span>
                    logs:
                </p>
                : ''
            )
        }
        <ul className="log-list">
            {
                MIAlogs && MIAlogs.length > 0 && MIAlogs.map((log) => {
                    return (
                        <li className="log" key={log._id}>
                            <ul className="log-values">
                                <li className="full-row white">
                                    <b>Times</b>
                                    <div className="times">
                                        <p>SQL Query: <span>{log.times.endQuerySQL - log.times.startQuerySQL}ms</span></p>
                                        <p>Response: <span>{log.times.endResponse - log.times.startResponse}ms</span></p>
                                        <p>Total: <span>{log.times.endRequest - log.times.startRequest}ms</span></p>
                                    </div>
                                </li>
                                <li className={log?.anonimousUserID ? 'break-word yellow' : 'gray'}>
                                    <b>Anonimous User ID</b>
                                    { log?.anonimousUserID }
                                </li>
                                <li className={log?.userEmail ? 'yellow' : 'gray'}>
                                    <b>User Email</b>
                                    { log?.userEmail }
                                </li>
                                <li className="yellow">
                                    <b>Fecha</b>
                                    { moment(log?.date).format('MMMM DD - HH:mm:ss - YYYY') }
                                </li>
                                <li className="break-word white">
                                    <b>ID</b>
                                    {log?._id}
                                </li>
                                <li className={log?.rating === true ? 'green' : log?.rating === false ? 'red' : 'gray' + ' white' }>
                                    <b>Rating</b>
                                    {log?.rating === true ? 'Good' : log?.rating === false ? 'Bad' : '-' }
                                </li>
                                <li className={ log?.navigator ? 'white' : 'gray' }>
                                    <b>Navegador</b>
                                    {log?.navigator}
                                </li>
                                <li className={ log?.suggestionID ? 'break-word white' : 'gray'}>
                                    <b>suggestion ID</b>
                                    {log?.suggestionID}
                                </li>
                                <li className={ log?.testID ? 'break-word white' : 'gray'}>
                                    <b>test ID</b>
                                    {log?.testID}
                                </li>
                                <li className={`${log?.userQuery ? 'white' : 'gray'} full-row`}>
                                    <b>User Query</b>
                                    {log?.userQuery?.consulta}
                                </li>
                                {
                                    log?.attemptsListSQL?.length > 0 && log?.attemptsListSQL.map((attempt, index) => (
                                        <li className={`${attempt.errGenerateSQL || attempt.errorGetProgramsList ? 'red' : 'white'} full-row`}>
                                            <p>
                                                <span>Attempt SQL {attempt.attempt}</span>
                                            </p>
                                            <p>
                                                {attempt.querySQL}
                                            </p>
                                            {
                                                attempt.errGenerateSQL &&
                                                    <p>
                                                        <span>{attempt.errGenerateSQL}</span>
                                                    </p>
                                            }
                                            {
                                                attempt.errorGetProgramsList &&
                                                    <p>
                                                        <span>{attempt.errorGetProgramsList}</span>
                                                    </p>
                                            }
                                        </li>
                                    ))
                                }
                                <li className={ log?.response ? 'break-word white full-row' : 'gray full-row'}>
                                    <b>Response</b>
                                    {
                                        log?.response &&
                                        <button className="btn-show-data" onClick={() => setShowResponse(!showResponse)}>
                                            {showResponse ? 'Hide' : 'Show'}
                                        </button>
                                    }
                                    {
                                        showResponse &&
                                    <div className="markdown">
                                        <Markdown rehypePlugins={[rehypeRaw]}>
                                            {
                                                log?.response
                                            }
                                        </Markdown>

                                    </div>
                                    }
                                </li>
                                <li className={log?.responseError ? 'red break-word' : 'gray break-word'}>
                                    <b>Response Error</b>
                                    {log?.errorResponse}
                                </li>
                                <li className={ log?.programsList?.rows.length ? 'break-word white full-row' : 'gray full-row'}>
                                    <b>Programs List</b>
                                    <p>
                                        There are {log?.programsList?.rows.length} programs
                                    </p>
                                    {
                                        log?.programsList?.rows.length &&
                                        <button className="btn-show-data" onClick={() => setShowProgramsList(!showProgramsList)}>
                                            {showProgramsList ? 'Hide' : 'Show'}
                                        </button>
                                    }
                                    {
                                        showProgramsList &&
                                        <ul className="markdown background">
                                            {
                                                log?.programsList?.rows.length > 0 && log?.programsList?.rows.map((program, index) => {
                                                    return <Program program={program} />
                                                })
                                            }
                                        </ul>
                                    }
                                </li>
                            </ul>
                        </li>
                    )
                })
            }
        </ul>
        <style jsx>{`
            h3 {
                font-size: 1.2em;
                text-align: center;
                font-weight: 500;
                text-transform: capitalize;
                margin-bottom: .5em;
            }

            .description {
                font-weight: 400;
                font-size: .9em;
                margin-bottom: 1em
            }

            form {
                display: grid;
                justify-content: center;
                gap: .5em;
            }

            .wrapper-date-inputs, .wrapper-hour-inputs {
                margin: auto;
            }

            .wrapper-date-inputs input {
                width: 3em;
                background: var(--dark-blue);
                color: var(--white);
                text-align: center;
                border-radius: .5em;
                margin-right: .1em;
            }

            .wrapper-hour-inputs input {
                text-align: center;
                border-radius: .5em;
                background: var(--dark-blue);
                color: var(--white);
                margin-right: .1em;
            }
            
            .btn-view-logs {
                background-color: var(--yellow);
                border-radius: 1em;
                padding: .5em 1em;
            }

            .number-logs {
                margin: 0 .3em;
                font-weight: 600;
                font-size: 1.3em;
                color: var(--dark-blue);
            }

            .log-list {
                margin-top: 1em;
                display: grid;
                gap: 1em;
            }

            .log {
                background-color: var(--dark-blue);
                color: var(--white);
                padding: 1.5em;
                border-radius: .5em;
            }

            .log > li {
                display: grid;
                justify-content: start;
                padding: .5em;
                border-radius: .5em;
            }

            .log li b {
                font-weight: 600;
                font-size: 1.2em;
                line-height: 1em;
            }

            .log-values {
                display: grid;
                gap: 1em;
                grid-template-columns: 1fr 1fr;
            }

            .log-values > li {
                position: relative;
                display: grid;
                gap: .5em;
                padding: .5em;
                border-radius: .5em;
            }

            .btn-show-data {
                background-color: var(--yellow);
                border-radius: .5em;
                justify-self: start;
            }
            
            .times {
                display: flex;
                justify-content: space-around;
                gap: .5em;
                padding: 
            }

            .times p {
                display: grid;
                text-align: center;
            }

            .times span {
            }

            b {
                font-weight: 600;
                text-transform: capitalize;
                text-align: center;
            }

            .break-word {
                word-break: break-all;
            }

            .full-row {
                grid-column: 1/3;
            }

            .white {
                border: .15em solid var(--white);
                background: var(--transparent-white);
            }

            .yellow {
                border: .15em solid var(--dark-yellow);
                color: var(--dark-yellow);
                background: var(--transparent-dark-yellow);
            }

            .green {
                border: .15em solid var(--green);
                color: var(--green);
                background: var(--transparent-green);
            }

            .red {
                color: red;
                border: .15em solid var(--red);
                background: var(--transparent-red);
            }

            .gray {
                color: var(--gray);
                border: .15em solid var(--transparent-gray);
                background: var(--transparent-gray);
            }

            .center {
                text-align: center;
            }
        `}</style>
    </>
}

export default MIALogs
