import moment from 'moment'
import { useState } from 'react'
import { useForm } from 'react-hook-form'

const VocationalTestLogs = () => {
    const [VocationaTestLogs, setVocationaTestLogs] = useState(null)

    const {
        register,
        handleSubmit
        // formState: { errors }
    } = useForm()

    const getLogs = async (formData) => {
        if (formData.day.length < 2) formData.day = '0' + formData.day
        if (formData.month.length < 2) formData.month = '0' + formData.month

        const params = new URLSearchParams(formData)
        const result = await fetch('/api/vocational-test?' + params.toString())
        const data = await result.json()
        const updateDates = data.testList.map(data => {
            const dateUpdated = data.startedAt ? new Date(data.startedAt.replace('Z', '-05:00')) : ''
            data.startedAt = dateUpdated

            return data
        })
        const sortedDates = updateDates.sort((dateA, dateB) => dateA.startedAt - dateB.startedAt)

        setVocationaTestLogs(sortedDates.reverse() ?? [])
    }

    return <>
        <h3>Vocational Test Logs</h3>
        <p className="description">
            In this section, you can view logs generated by Vocational Test. You can filter by date and time.
        </p>
        <form onSubmit={handleSubmit(getLogs)}>
            <div className="wrapper-date-inputs">
                <input type="text" {...register('day', {
                    value: new Date().getDate().toString()
                })} />
                -
                <input type="text" {...register('month', {
                    value: new Date().getMonth() + 1 + ''
                })} />
                -
                <input type="text" {...register('year', {
                    value: new Date().getFullYear().toString()
                })} />
            </div>
            <div className="wrapper-hour-inputs">
                <input type="time" {...register('start', {
                    value: '00:00'
                })}/>
                -
                <input type="time" {...register('end', {
                    value: '23:59'
                })}/>
            </div>
            <button className="btn-view-logs" type="submit">View Logs</button>
        </form>
        {
            VocationaTestLogs && (VocationaTestLogs.length > 0
                ? <p >
                    Showing
                    <span className="number-logs">
                        {VocationaTestLogs.length}
                    </span>
                    logs:
                </p>
                : ''
            )
        }
        <ul className="log-list">
            {
                VocationaTestLogs && VocationaTestLogs.length > 0 && VocationaTestLogs.map((vocationalTest) => {
                    return (
                        <li className="log" key={vocationalTest._id}>
                            <ul className="log-values">
                                <li className={`${vocationalTest.duration ? 'white' : 'red'} full-row`}>
                                    <b>Times</b>
                                    <div className="times">
                                        <p>Duration: <span>{Math.floor(vocationalTest?.duration / 60000)} min</span></p>
                                    </div>
                                </li>
                                <li className="break-word white center full-row">
                                    <b>Responded Questions</b>
                                    {vocationalTest?.questionsListAleatory.reduce((acc, question) => acc + (question.value ? 1 : 0), 1)}
                                    /
                                    {vocationalTest?.questionsNumber || 90}
                                </li>
                                <li className={vocationalTest?.anonimousUserID ? 'break-word yellow' : 'gray'}>
                                    <b>Anonimous User ID</b>
                                    { vocationalTest?.anonimousUserID }
                                </li>
                                <li className={vocationalTest?.userEmail ? 'yellow' : 'gray'}>
                                    <b>User Email</b>
                                    { vocationalTest?.userEmail }
                                </li>
                                <li className="yellow">
                                    <b>Fecha</b>
                                    { moment(vocationalTest?.startedAt).format('MMMM DD - HH:mm:ss - YYYY') }
                                </li>
                                <li className="break-word white">
                                    <b>ID</b>
                                    {vocationalTest?._id}
                                </li>
                            </ul>
                        </li>
                    )
                })
            }
        </ul>
        <style jsx>{`
            h3 {
                font-size: 1.2em;
                text-align: center;
                font-weight: 500;
                text-transform: capitalize;
                margin-bottom: .5em;
            }

            .description {
                font-weight: 400;
                font-size: .9em;
                margin-bottom: 1em
            }

            form {
                display: grid;
                justify-content: center;
                gap: .5em;
            }

            .wrapper-date-inputs, .wrapper-hour-inputs {
                margin: auto;
            }

            .wrapper-date-inputs input {
                width: 3em;
                background: var(--dark-blue);
                color: var(--white);
                text-align: center;
                border-radius: .5em;
                margin-right: .1em;
            }

            .wrapper-hour-inputs input {
                text-align: center;
                border-radius: .5em;
                background: var(--dark-blue);
                color: var(--white);
                margin-right: .1em;
            }
            
            .btn-view-logs {
                background-color: var(--yellow);
                border-radius: 1em;
                padding: .5em 1em;
            }

            .number-logs {
                margin: 0 .3em;
                font-weight: 600;
                font-size: 1.3em;
                color: var(--dark-blue);
            }

            .log-list {
                margin-top: 1em;
                display: grid;
                gap: 1em;
            }

            .log {
                background-color: var(--dark-blue);
                color: var(--white);
                padding: 1.5em;
                border-radius: .5em;
            }

            .log > li {
                display: grid;
                justify-content: start;
                padding: .5em;
                border-radius: .5em;
            }

            .log li b {
                font-weight: 600;
                font-size: 1.2em;
                line-height: 1em;
            }

            .log-values {
                display: grid;
                gap: 1em;
                grid-template-columns: 1fr 1fr;
            }

            .log-values > li {
                position: relative;
                display: grid;
                gap: .5em;
                padding: .5em;
                border-radius: .5em;
            }

            .btn-show-data {
                background-color: var(--yellow);
                border-radius: .5em;
                justify-self: start;
            }
            
            .times {
                display: flex;
                justify-content: space-around;
                gap: .5em;
                padding: 
            }

            .times p {
                display: grid;
                text-align: center;
            }

            .times span {
            }

            b {
                font-weight: 600;
                text-transform: capitalize;
                text-align: center;
            }

            .break-word {
                word-break: break-all;
            }

            .full-row {
                grid-column: 1/3;
            }

            .white {
                border: .15em solid var(--white);
                background: var(--transparent-white);
            }

            .yellow {
                border: .15em solid var(--dark-yellow);
                color: var(--dark-yellow);
                background: var(--transparent-dark-yellow);
            }

            .green {
                border: .15em solid var(--green);
                color: var(--green);
                background: var(--transparent-green);
            }

            .red {
                color: red;
                border: .15em solid var(--red);
                background: var(--transparent-red);
            }

            .gray {
                color: var(--gray);
                border: .15em solid var(--transparent-gray);
                background: var(--transparent-gray);
            }

            .center {
                text-align: center;
            }
        `}</style>
    </>
}

export default VocationalTestLogs
