/*
texto para generar el json:
De acuerdo al test vocacional de Holland, asigna cada uno de los siguientes programas a su respectivo tipo "RIASEC" (realista, investigador, artistico, social, emprendor, convencional). crea un JSON en el que cada clave sea un tipo y su valor sea la lista de programas asignados a este tipo. cada programa solo puede tener un tipo:
*/
export const technicalPrograms = {
    realista: [
        'instalación y mantenimiento de redes y computadores',
        'producción y transformación del acero',
        'mecatrónica',
        'instalación de redes eléctricas de baja y media tensión',
        'instalación de sistemas de energía renovable',
        'procesamiento del café y cacao',
        'procesamiento agroindustrial',
        'producción agrícola',
        'producción cafetera',
        'manejo y conservación de productos agroindustriales',
        'mineria sostenible',
        'producción acuícola continental',
        'piscicultura continental',
        'operación de equipos industriales y actividades mineras',
        'operación de maquinas y herramientas asociadas a mineria',
        'operacion de seguridad minera',
        'servicio automotriz',
        'manejo de vehículos de carga pesada',
        'transporte terrestre de carga',
        'mantenimiento mecanico',
        'producción de ganadería sostenible',
        'manejo ecológico de plagas',
        'muestreo y monitoreo ambiental',
        'perforación de pozos petrolíferos',
        'instalación de redes de telecomunicaciones',
        'operación de almacenes y transporte',
        'acuicultura',
        'manejo de suelos y aguas',
        'producción agroecológica de cultivos',
        'mantenimiento electronico',
        'mantenimiento de computadores e instalación y configuración de redes lan',
        'mantenimiento electrónico',
        'investigacion y seguridad',
        'mantenimiento mecanico aplicado a la operación de armas de artillería',
        'el mantenimiento y operación de armas basicas de infanteria',
        'mecanica diesel',
        'produccion de frutas y hortalizas',
        'seguridad y salud en el trabajo',
        'mantenmiento electromecánico',
        'redes eléctricas de distribución de energía',
        'instalación y mantenimiento de redes de telecomunicaciones',
        'mantenimiento de sistemas informaticos',
        'mantenimiento electrónico industrial',
        'instrumentacion industrial',
        'electricidad industrial',
        'electromecánica',
        'electronica',
        'mantenimiento de computadores y redes',
        'operación de plantas petroquímicas',
        'operaciones agroindustriales',
        'seguridad industrial',
        'mantenimiento de sistemas mecatronicos',
        'procesos de producción',
        'soporte de telecomunicaciones',
        'construccion de sofware',
        'operacion de sistemas de manejo ambiental',
        'soporte informático',
        'operaciones logísticas',
        'operaciones aduaneras y de comercio internacional',
        'producción gráfica',
        'mantenimiento de redes',
        'mantenimiento de sistemas mecatrónicos',
        'mecánica de vehículos híbridos y eléctricos',
        'conducción de vehículos de transporte terrestre',
        'instalaciones eléctricas para sistemas renovables',
        'mantenimiento de sistemas mecatrónicos industriales',
        'mecánica automotriz',
        'procesos de redes y comunicaciones',
        'mantenimiento industrial',
        'producción agroindustrial de alimentos',
        'seguridad industrial',
        'operación de equipos de auscultación minero energético',
        'operación de equipos de muestreo minero energétic0',
        'procesos de manufactura',
        'electrónica industrial',
        'mantenimiento industrial',
        'procesos de soldadura',
        'procesos viales y de transporte',
        'construcción de edificaciones',
        'monitoreo agrícola',
        'monitoreo ambiental',
        'mantenimiento de sistemas informáticos',
        'operaciones portuarias',
        'operaciones de procesos industriales',
        'producción agropecuaria sostenible',
        'extracción y maquinaria minero aurífera',
        'procesos de producción agrícola',
        'mecánica automotriz',
        'mecánica de motos',
        'operación de procesos de producción',
        'montaje y mantenimiento de energías renovables',
        'implementación de sistemas de telecomunicaciones',
        'instalación y mantenimiento de redes de telecomunicaciones',
        'seguridad e higiene industrial',
        'construcción',
        'producción de petróleo y gas',
        'telecomunicaciones',
        'operaciones logísticas',
        'instalación y configuración de redes',
        'laboratorio',
        'producción de materias primas agroindustriales',
        'microfundición de metales',
        'entrenamiento de fútbol',
        'electromedicina',
        'tecnología de plásticos',
        'telecomunicaciones',
        'pastelería y panadería',
        'control de la calidad de alimentos',
        'instalación y mantenimiento eléctrico',
        'soporte de infraestructuras informáticas y redes de datos'
    ],
    investigador: [
        'procesos metrológicos',
        'peritaje ambiental',
        'control industrial',
        'investigación judicial',
        'procesos de extracción de biomasa energética',
        'procesos de gestión publica',
        'procesos de gestión pública territorial',
        'balistica',
        'dactiloscopia',
        'explosivos',
        'fotografia e imagen forense',
        'identificacion de automotores',
        'topografia forense',
        'inteligencia y contrainteligencia policial',
        'análisis de mediciones de la producción minero energética',
        'criminalística (ciclo propedéutico)',
        'promotoria ambiental',
        'procesos de importaciones y exportaciones',
        'procesos agroforestales',
        'medición del impacto ambiental',
        'procesos de desarrollo de producto',
        'procesos de cloud computing',
        'procesos de inteligencia de negocios',
        'manejo de la prevención de riesgos laborales',
        'procesos de manejo ambiental',
        'gestión ambiental',
        'procesos ambientales',
        'prevención y rehabilitación',
        'registro de procesos productivos',
        'producción de contenidos informativos',
        'procesos ambientales',
        'criminalística',
        'higiene y seguridad en el trabajo',
        'formulación y gestión de proyectos',
        'procesos de la seguridad y salud en el trabajo',
        'sistema indígena de salud propia intercultural - SISPI'
    ],
    artistico: [
        'expresión artística, corporal y vocal para la escena',
        'expresión gráfica arquitectónica',
        'ejecución de proyectos culturales y creativos',
        'animación y multimedia',
        'video, discjockey y sonido',
        'construcción de proyectos arquitectónicos',
        'documentación de proyectos urbanísticos',
        'producción de piezas multimedia',
        'producción de sonido en vivo y audiovisual',
        'producción grafica',
        'montaje escenico',
        'fabricación digital e impresión 3d',
        'producción gráfica y multimedial',
        'producción de contenidos audiovisuales',
        'producción de objetos para la interacción digital',
        'producción de objetos para las prácticas visuales',
        'producción para las prácticas musicales',
        'producción sonora para contenidos digitales',
        'actuacion para las practicas escenicas teatrales',
        'cocina',
        'mesa y bar',
        'producción fotográfica',
        'realizacion y produccion en television',
        'producción gráfica',
        'animación digital y comunicación grafica',
        'fotografia y camarografia',
        'expresión gráfica y digital',
        'dibujo arquitectónico y decoración',
        'dibujo mecánico y de herramientas industriales',
        'dibujo arquitectónico y decoración',
        'producción de audio y video',
        'diseño de modas',
        'diseño gráfico',
        'producción en diseño de interiores',
        'producción en diseño industrial',
        'producción en publicidad',
        'producción en publicidad y medios digitales',
        'producción multimedial',
        'expresión digital y adaptación de espacios',
        'expresión publicitaria',
        'procesos de diseño gráfico',
        'procesos de producción gráfica',
        'decoración de ambientes',
        'arte gráfico y publicitario',
        'diseño de vestuario y patronaje',
        'diseño digital',
        'diseño gráfico',
        'danza contemporánea (cuerpo creador)',
        'medios audiovisuales',
        'producción publicitaria',
        'producción publicitaria digital',
        'técnicas artísticas',
        'producción de televisión',
        'producción de alta costura',
        'diseño web y multimedia',
        'estética cosmetológica',
        'cosmetología y estética corporal'
    ],
    social: [
        'atención prehospitalaria',
        'cuidado y desarrollo de la primera infancia',
        'atención al cliente',
        'operacion turistica',
        'operación de empresas turísticas',
        'operación de servicios de guianza',
        'operación integral de ventas turísticas',
        'entrenamiento deportivo',
        'masoterapia',
        'hotelería y turismo',
        'procesos administrativos de salud',
        'procesos administrativos en salud',
        'organización de certámenes',
        'operación de servicios turísticos',
        'operación turística',
        'ejecución de proyectos culturales',
        'secretariado ejecutivo',
        'turismo',
        'facturación y cartera de servicios de salud',
        'procesos administrativos de diseño de modas',
        'procesos de diseño de modas',
        'promoción de proyectos sociales',
        'gastronomia',
        'procesos hoteleros y de servicios',
        'servicios a bordo',
        'servicios turísticos y hoteleros',
        'atención integral a la primera infancia',
        'operación de servicios comunitarios',
        'entrenamiento deportivo',
        'operación de servicios comunitarios',
        'atención y cuidado a la primera infancia',
        'hotelería y turismo',
        'operación turística y hotelera',
        'operación de servicios turísticos y hoteleros',
        'procesos judiciales',
        'hotelería y turismo',
        'gestión de bares y restaurantes',
        'operación de servicios gastronómicos',
        'salud oral',
        'servicios turísticos y hoteleros',
        'operaciones administrativas de la salud',
        'servicios administrativos de salud',
        'promoción social',
        'procesos turísticos y hoteleros',
        'operación hotelera',
        'procesos hoteleros y turísticos',
        'operación de mercadeo y ventas'
    ],
    emprendedor: [
        'procesos comerciales y financieros',
        'gestión comercial del sector agropecuario',
        'logística de agronegocios',
        'logistica de producción',
        'operación del transporte multimodal',
        'contabilidad',
        'programacion web',
        'operación gastronómica',
        'operacion de procesos gastronomicos',
        'gestión de aduanas y comercio exterior',
        'comercio exterior',
        'gestion empresarial',
        'procesos logisticos',
        'comercio internacional',
        'operaciones de comercio exterior',
        'manejo de microcréditos',
        'operaciones comerciales',
        'logistica empresarial',
        'procesos empresariales',
        'operación de procesos empresariales',
        'operaciones del comercio exterior',
        'procesos de comercio exterior y logistica',
        'distribución logística y comercial',
        'operación de comercio electrónico',
        'mercadotecnia',
        'ventas y negocios',
        'procesos empresariales para mipymes',
        'biocomercio',
        'operaciones turísticas',
        'procesos de mercadeo digital',
        'gestión empresarial',
        'mercadeo',
        'operaciones de comercio exterior',
        'operaciones logisticas',
        'logística internacional de comercio',
        'turismo sostenible',
        'operación de cocina y restauracion',
        'mercadeo de agronegocios',
        'procesos de marketing internacional',
        'procesos de comercio exterior',
        'asesoría comercial para soluciones digitales',
        'creación de contenidos digitales',
        'relacionamiento digital con clientes enfoque CRM',
        'procesos de mercadeo',
        'procesos de mercadeo digital',
        'mercadeo y ventas',
        'mercadeo y publicidad',
        'procesos de mercadeo y estrategias comerciales',
        'comercio y negocios internacionales',
        'gestión empresarial',
        'logística de comercio exterior',
        'operaciones de comercio digital',
        'procesos comunicativos y comerciales',
        'producción y comercialización de la moda',
        'gestión aduanera y zonas francas',
        'gestión comercial y logística',
        'comercio exterior y negocios internacionales',
        'procesos de comercio exterior',
        'procesos empresariales',
        'procesos empresariales rurales'
    ],
    convencional: [
        'procesos administrativos',
        'archivística',
        'documentologia',
        'configuración de servicios para comercio electrónico',
        'soporte para el aseguramiento y control de la calidad',
        'procesos administrativos de salud',
        'servicio de policia',
        'servicio de policía',
        'seguridad integral canina',
        'seguridad vial',
        'protección y seguridad a personas e instalaciones',
        'control ambiental',
        'tránsito, transporte y seguridad vial',
        'procesos administrativos',
        'documentación de la calidad',
        'operación y mantenimiento de bases de datos',
        'operaciones administrativas y financieras de la salud',
        'contabilidad',
        'procesos administrativos',
        'registro y control de procesos productivos',
        'sistemas',
        'operación de procesos industriales',
        'procesos financieros',
        'procesos organizacionales',
        'procesos contables',
        'procesos administrativos',
        'nomina y prestaciones sociales',
        'procesos aduaneros y tributarios',
        'procesos contables y tributarios',
        'secretariado ejecutivo sistematizado',
        'contabilidad y costos',
        'costos y contabilidad',
        'procesos administrativos de seguridad y salud en el trabajo',
        'procesos de sistemas informaticos',
        'procesos de sistemas informáticos',
        'soporte y procesos informáticos',
        'operaciones contables',
        'procesos contables y tributarios',
        'operación de procesos contables',
        'procesos administrativos empresariales',
        'procesos administrativos en salud',
        'contabilidad sistematizada',
        'procesos de talento humano',
        'procesos logísticos',
        'operaciones fintech',
        'operaciones de comercio electrónico',
        'avalúos inmobiliarios urbanos y rurales',
        'aseguramiento y procesamiento de bases de datos',
        'soporte de sistemas informáticos',
        'soporte de sistemas informáticos y de comunicaciones',
        'contabilidad y finanzas',
        'procesos contables',
        'asistente administrativo bilingüe',
        'procesos administrativos de talento humano',
        'soporte de documentación de calidad',
        'procesos administrativos en salud',
        'de procesos administrativos portuarios',
        'de operaciones en comercio exterior',
        'procesos administrativos de la seguridad social',
        'operaciones contables y financieras',
        'de procesos administrativos en hotelería y turismo',
        'procesos administrativos de obras de construcción',
        'gestión financiera',
        'logística de producción',
        'administración de empresas',
        'procesos administrativos y financieros',
        'procesos bancarios y financieros',
        'procesos contables',
        'procesos financieros',
        'procesos logísticos y de comercio exterior',
        'contabilidad y tributaria',
        'soporte de hardware y software',
        'soporte de sistemas electrónicos',
        'sistemas de cómputo',
        'operación logística'
    ]
}
