export const univeristyPrograms = {
    realista: [
        'ingeniería metalurgica',
        'ingenieria electromecanica',
        'ingenieria de minas',
        'ingenieria agropecuaria',
        'ingenieria de sistemas',
        'ingeniería electrónica y telecomunicaciones',
        'ingeniería en agroecología',
        'ingeniería en automatica industrial',
        'ingeniería civil',
        'ingeniería de manufactura',
        'ingeniería en procesos agroindustriales',
        'ingeniería en procesos sostenibles de las maderas',
        'ingeniería mecatrónica',
        'ingeniería de alimentos',
        'ingenieria de sistemas y computacion',
        'ingeniería en informática',
        'ingeniería ambiental',
        'ingeniería mecánica',
        'ingeniería química',
        'ingenieria biomédica',
        'ingeniería en mecatronica',
        'ingeniería en multimedia',
        'ingenieria en telecomunicaciones',
        'ingeniería industrial',
        'ingeniería informática',
        'ingeniería agroforestal',
        'ingeniería de telecomunicaciones e informática',
        'ingeniería agroindustrial',
        'ingeniería de procesos',
        'ingeniería forestal',
        'ingeniería ambiental y sanitaria',
        'ingeniería de alimentos',
        'ingenieria de materiales',
        'ingenieria de telecomunicaciones',
        'ingeniería oceanográfica',
        'ingeniería sanitaria',
        'ingeniería urbana',
        'ingeniería geomática',
        'ingeniería sanitaria y ambiental',
        'ingenieria en agronegocios',
        'ingeniería biomédica',
        'ingeniería de la construcción',
        'ingeniería de procesos de refinación y petroquímicos',
        'microbiología y bioanálisis',
        'producción agroindustrial',
        'ingeniería agronómica',
        'ingeniería en producción acuícola',
        'ingeniería topográfica y geomática',
        'ingeniería biotecnológica',
        'ingeniería aeroespacial',
        'ingeniería energética',
        'ingeniería marina-costera',
        'ingeniería pesquera',
        'ingeniería de sistemas y computación',
        'ingeniería de software',
        'ingeniería electrónica',
        'ingeniería civil articulado por ciclos propedéuticos con el programa de tecnología en construcciones civiles',
        'ingeniería catastral y geodesia',
        'ingeniería de producción',
        'ingeniería eléctrica',
        'ingeniería en telecomunicaciones',
        'ingeniería en control y automatización',
        'ingeniería en telemática',
        'ingeniería sanitaria',
        'ingeniería topográfica',
        'ingeniería en redes y telecomunicaciones',
        'ingeniería en higiene y seguridad industrial',
        'ingeniería en informática',
        'ingeniería en logística y operaciones',
        'ingeniería en automatización',
        'ingeniería en energía',
        'ingeniería en bioproducción',
        'ingeniería de diseño e innovación',
        'ingeniería de procesos',
        'ingeniería matemática',
        'ingeniería aeronautica',
        'ingeniería en ciencia de datos',
        'ingeniería en nanotecnología',
        'ingeniería agronómica',
        'ingeniería de diseño de producto',
        'ingeniería en diseño de entretenimiento digital',
        'ingeniería en bioproducción',
        'ingeniería de procesos',
        'biotecnología',
        'ingeniería de sistemas energéticos',
        'ingeniería en energías',
        'ingeniería multimedia',
        'ingeniería de datos y software',
        'ingeniería de sistemas cibernéticos',
        'ingeniería de sonido',
        'ingeniería en seguridad de la información',
        'ingeniería logística',
        'ingeniería ambiental',
        'ingeniería de sistemas y telecomunicaciones',
        'ingeniería en analítica de datos',
        'ingeniería en multimedia',
        'ciencias culinarias de la gastronomía',
        'gestión ambiental',
        'ingeniería biomedica',
        'ingeniería geográfica y ambiental',
        'ingeniería en automatización',
        'ingeniería en energías',
        'ingeniería electrónica',
        'ingeniería en tecnologías de la información y las comunicaciones',
        'ingeniería en energías renovables y sustentabilidad ambiental',
        'ingeniería mecánica',
        'ingeniería agroalimentaria',
        'ingeniería en energía',
        'ingeniería en energía y sostenibilidad',
        'ingeniería electromecánica',
        'ingeniería en control y automatización industrial',
        'ingeniería en energía inteligente',
        'ingeniería telemática',
        'ingeniería civil',
        'ingeniería naval',
        'ingeniería electromecánica',
        'ingeniería civil (por ciclos propedeúticos)',
        'ingeniería agroforestal',
        'ingeniería industrial',
        'ingeniería comercial',
        'ingeniería de productividad y calidad',
        'ingeniería en automatización y control',
        'ingeniería de producción',
        'ingeniería en seguridad y salud en el trabajo',
        'ingeniería ambiental y de saneamiento',
        'ingeniería en logística',
        'ingeniería agrícola',
        'ingeniería de mantenimiento',
        'ingeniería robótica',
        'ingeniería de minas',
        'ingeniería geológica',
        'ingeniería en telecomunicaciones',
        'ingeniería en ciencia de datos',
        'ingeniería en seguridad de la información',
        'ingeniería en analítica de datos',
        'ingeniería de petróleos',
        'ingeniería de telecomunicaciones',
        'ingeniería industrial',
        'ingeniería electrónica',
        'ingeniería en inteligencia de negocios',
        'ingeniería estadística',
        'ingeniería biotecnológica',
        'ingeniería financiera',
        'ingeniería en energías renovables',
        'ingeniería en ciencias de la computación e inteligencia artificial',
        'ingeniería petroquímica',
        'ingeniería mecatrónica',
        'ingeniería de sistemas de información',
        'ingeniería aeronáutica',
        'ingeniería de gas y petróleo',
        'ingeniería de software y computación',
        'ingeniería informática',
        'ingeniería telemática',
        'ingeniería en sistemas de transporte',
        'ingeniería en topografía',
        'ingeniería en software',
        'profesional en criminalistica',
        'profesional en gestión de la seguridad y salud en el trabajo',
        'ingeniería de la calidad',
        'ingeniería de producción',
        'ingeniería electromecánica',
        'ingeniería electrónica',
        'ingeniería en diseño industrial',
        'química industrial',
        'administracion de sistemas informáticos',
        'ingeniería agroambiental',
        'ingeniería de procesos industriales',
        'ingeniería agronómica',
        'ingeniería en seguridad industrial e higiene ocupacional',
        'ingeniería en seguridad y salud para el trabajo',
        'ingeniería de sistemas y computación',
        'ingeniería de las artes digitales',
        'ingeniería en energías renovables',
        'ingeniería de polímeros',
        'ingeniería mecatrónica',
        'ciencias militares aeronáuticas',
        'ciencias militares',
        'ingenieria civil',
        'ingenieria naval',
        'oceanografia fisica',
        'ingenieria electrica por ciclos propedeuticos',
        'ingeniería de petróleo y gas',
        'ingeniería electrónica y telecomunicaciones'
    ],
    investigador: [
        'licenciatura en ciencias naturales y educacion ambiental',
        'licenciatura en filosofía',
        'licenciatura en matemáticas',
        'licenciatura en psicopedagogia con enfasis en asesoria educativa',
        'licenciatura en lenguas modernas con énfasis en inglés',
        'licenciatura en matematicas y fisica',
        'quimica industrial',
        'filosofía y letras',
        'licenciatura en lingüística y semiótica',
        'biologia aplicada',
        'matemática aplicada',
        'antropología',
        'geografía',
        'matemáticas aplicadas y computacionales',
        'biología',
        'astronomía',
        'bioingenieria',
        'microbiología',
        'microbiologia industrial y ambiental',
        'ingeniería bioquímica',
        'química farmacéutica',
        'economía',
        'licenciatura en filosofía',
        'matemáticas con énfasis en estadística',
        'lingüística y literatura',
        'ciencia de datos',
        'licenciatura en matemáticas',
        'licenciatura en ciencias sociales',
        'licenciatura en ciencias sociales y desarrollo local',
        'historia y patrimonio',
        'historia y archivística',
        'ciencia de la información y la documentación, bibliotecología y archivística',
        'ecología',
        'microbiología industrial',
        'química farmacéutica',
        'matemáticas aplicadas',
        'filosofía',
        'ciencias cognitivas en contextos educativos',
        'administración ambiental y de los recursos naturales',
        'licenciatura en biología',
        'licenciatura en filosofía y letras',
        'licenciatura en educación religiosa',
        'biología ambiental',
        'biología marina',
        'arqueología',
        'conservación y restauración de patrimonio cultural mueble',
        'biología ambiental',
        'química ambiental',
        'ciencias políticas',
        'ciencias políticas',
        'matemáticas aplicadas y ciencias de la computación',
        'estadística y ciencias actuariales',
        'ciencias del sistema tierra',
        'ciencia política y gobierno',
        'filosofía y humanidades',
        'ciencias de la computación e inteligencia artificial',
        'innovación y economía de datos',
        'innovación y tecnología económica',
        'investigación criminal',
        'microbiología',
        'bacteriología',
        'bioquímica',
        'computación científica',
        'geociencias',
        'licenciatura en ciencias sociales con énfasis en historia',
        'licenciatura en filosofía',
        'licenciatura en ciencias sociales',
        'licenciatura en física',
        'licenciatura en tecnología e informática',
        'biología ambiental',
        'ciencia política y relaciones internacionales',
        'ciencias ambientales',
        'ciencias del deporte',
        'ingeniería geográfica y ambiental',
        'administración ambiental y de los recursos naturales',
        'agronomía',
        'biotecnología',
        'ecología',
        'geopolítica',
        'economía pública',
        'criminología',
        'química',
        'desarrollo territorial y construcción de paz',
        'psicología',
        'estudios políticos',
        'licenciatura en filosofía',
        'contaduría pública y finanzas internacionales',
        'matemáticas y ciencias de la computación',
        'química y farmacia',
        'matemáticas aplicadas en ciencia de datos',
        'estudios en filosofía',
        'licenciatura en educación preescolar',
        'ciencia de la información y bibliotecología',
        'química industrial',
        'profesional en lenguas modernas',
        'licenciatura en pedagogía infantil',
        'ingenieria naval',
        'oceanografia fisica',
        'ciencias politicas y relaciones internacionales',
        'ingeniería de software y datos',
        'profesional en sistemas de informacion organizacional'
    ],
    artístico: [
        'licenciatura en educación artística',
        'licenciatura en educación física, lúdica y deporte',
        'licenciatura en educación física, recreación y deporte',
        'licenciatura en educación física, recreación y deportes',
        'licenciatura en etnoeducación',
        'licenciatura en lenguas modernas con énfasis en inglés y francés',
        'licenciatura en linguística y semiotica',
        'diseño visual',
        'licenciatura en educación física, recreación y deportes',
        'licenciatura en música',
        'licenciatura en educación física deportes y recreación',
        'licenciatura en artes',
        'licenciatura en artes escénicas',
        'licenciatura en artes plásticas',
        'licenciatura en danza',
        'licenciatura en música',
        'arte dramático',
        'arte dramático',
        'diseño digital y multimedia',
        'creación digital',
        'diseño gráfico',
        'licenciatura en música',
        'licenciatura en artes escénicas',
        'licenciatura en artes plásticas',
        'danza',
        'licenciatura en arte dramático',
        'licenciatura en literatura',
        'artes plásticas',
        'artes visuales',
        'comunicación social - periodismo',
        'licenciatura en educación artística',
        'cine y audiovisuales',
        'gestión cultural y de industrias creativas',
        'arte danzario',
        'artes escénicas',
        'artes musicales',
        'artes plásticas y visuales',
        'estudios musicales',
        'diseño de comunicación visual',
        'gastronomía y artes culinarias',
        'producción audiovisual interactiva',
        'diseño gráfico',
        'cine y televisión',
        'diseño interactivo',
        'diseño visual estratégico',
        'diseño y gestión de la moda',
        'estudios literarios y edición',
        'fotografía',
        'historia del arte',
        'realización en animación',
        'cine',
        'creación literaria',
        'diseño de experiencias interactivas',
        'diseño de vestuario',
        'diseño urbano y gestión del hábitat',
        'diseño de vestuario',
        'artes',
        'diseño',
        'creación',
        'teatro musical',
        'diseño de modas',
        'diseño digital',
        'diseño de comunicación',
        'formación musical',
        'intérprete profesional de la lengua de señas colombiana',
        'licenciatura digital en humanidades clásicas y lengua castellana',
        'licenciatura en español y lenguas extranjeras inglés y francés',
        'licenciatura en pedagogía digital para la primera infancia',
        'profesional en danza y performance',
        'creación de contenidos digitales',
        'diseño de interacción',
        'dirección y producción de cine y televisión',
        'producción y comunicación transmedia',
        'profesional en artes gastronómicas',
        'comunicación audiovisual',
        'comunicación social-periodismo',
        'diseño de espacios',
        'comunicación gráfica publicitaria',
        'comunicación y entretenimiento digital',
        'comunicación y lenguajes audiovisuales',
        'diseño y gestión de espacios',
        'diseño y gestión de la moda y el textil',
        'diseño y gestión del producto',
        'arte',
        'diseño crossmedia',
        'narrativas digitales',
        'diseño de espacios y escenarios',
        'profesional en gastronomía y alta cocina',
        'artes culinarias y gastronomía',
        'artes audiovisuales',
        'diseño de modas',
        'cine y comunicación digital',
        'comunicación publicitaria',
        'diseño de medios interactivos',
        'diseño de la comunicación gráfica',
        'narrativas y entretenimiento digital',
        'publicidad en medios digitales',
        'profesional en gastronomía y culinaria',
        'interpretación musical',
        'maestro en música',
        'licenciatura en educación artística y cultural',
        'comunicación audiovisual',
        'licenciatura en educación bilingüe',
        'profesional universitario en diseño audiovisual',
        'comunicación digital',
        'diseño hipermedia',
        'comunicación social - periodismo',
        'comunicación audiovisual y digital',
        'diseño de producto',
        'licenciatura en lengua castellana',
        'licenciatura en lenguas extranjeras con énfasis en inglés',
        'profesional en diseño visual',
        'profesional en diseño gráfico',
        'realización y producción musical',
        'animación',
        'comunicación visual',
        'licenciatura en educación artística',
        'licenciatura en educación básica con énfasis en educación artística',
        'licenciatura en educación básica con énfasis en humanidades y lengua castellana',
        'comunicación en narrativas transmedia',
        'comunicación publicitaria',
        'diseño estratégico',
        'diseño de espacios - escenario',
        'fotografía y comunicación visual',
        'profesional en diseño de vestuario',
        'profesional en gestión del diseño',
        'diseño de espacios escénicos y exhibición comercial',
        'profesional en diseño de modas',
        'artes de la grabación y producción musical',
        'diseño gráfico',
        'diseño y administración de negocios de la moda',
        'diseño de comunicación gráfica',
        'profesional en diseño visual digital',
        'profesional de diseño de modas',
        'profesional en diseño de espacios',
        'profesional en diseño industrial',
        'profesional en publicidad',
        'diseño visual digital',
        'profesional en dirección y producción de radio y televisión',
        'diseño gráfico',
        'gastronomía y cocina profesional',
        'creación escénica',
        'danza y dirección coreográfica',
        'profesional en gastronomía',
        'dirección y producción de medios audiovisuales',
        'profesional en comunicación social',
        'profesional en diseño gráfico',
        'profesional en publicidad y mercadeo',
        'ingeniería de las artes digitales',
        'animación',
        'fotografía para medios',
        'profesional en diseño de alta costura',
        'profesional en diseño de interiores',
        'profesional universitario en diseño textil para la industria',
        'profesional universitario en fotografía para medios',
        'fotografia',
        'diseño de moda',
        'profesional universitario diseño gráfico digital',
        'gestión cultural y comunicativa',
        'comunicación social y medios'

    ],
    social: [
        'licenciatura en educación infantil',
        'licenciatura en filosofía',
        'licenciatura en psicopedagogia con enfasis en asesoria educativa',
        'medicina veterinaria y zootecnia',
        'licenciatura en bilingüismo con énfasis en inglés',
        'licenciatura en etnoeducacion',
        'licenciatura en etnoeducacion y desarrollo comunitario',
        'comunicacion social',
        'licenciatura en ciencias naturales',
        'licenciatura en educación artística',
        'licenciatura en ciencias naturales y educacion ambiental',
        'comunicacion social y periodismo',
        'desarrollo familiar',
        'enfermería',
        'administración en salud',
        'relaciones internacionales y estudios politicos',
        'enfermería',
        'licenciatura en educación física recreación y deportes',
        'licenciatura en español y literatura',
        'licenciatura en lenguas modernas con enfasis en ingles',
        'fonoaudiología',
        'licenciatura en educación campesina y rural',
        'licenciatura en educacion fisica y deporte',
        'licenciatura en español e inglés',
        'psicología',
        'administración de empresas comerciales',
        'administración de empresas comerciales',
        'comercio internacional',
        'sociología',
        'administración de empresas turisticas y hoteleras',
        'administracion publica',
        'gestión cultural',
        'gestión en ecología y turismo',
        'periodismo',
        'español como lengua extranjera',
        'filologia hispanica',
        'gestión del emprendimiento y la innovación',
        'gestión cultural',
        'gestión en ecología y turismo',
        'comunicacion audiovisual y multimedial',
        'comunicaciones',
        'comunicación social - periodismo',
        'comunicacion social ¿ periodismo',
        'licenciatura en educacion especial',
        'licenciatura en lenguas extranjeras con énfasis en inglés y francés',
        'licenciatura en pedagogía de la madre tierra',
        'interpretación para sordos y guía-interpretación para sordociegos',
        'licenciatura en humanidades y lengua castellana',
        'licenciatura en lenguas extranjeras con enfasis en ingles y frances',
        'traduccion ingles-frances-español',
        'administración ambiental y sanitaria',
        'bibliotecologia',
        'licenciatura en educación popular',
        'licenciatura en español y filología',
        'licenciatura en historia',
        'licenciatura en lenguas extranjeras con énfasis en inglés y en francés',
        'primera infancia',
        'recreación',
        'administración de empresas culturales y creativas',
        'licenciatura en educación con énfasis en ciencias sociales y ambientales',
        'programa profesional universitario en lenguas extranjeras',
        'seguridad y salud en el trabajo',
        'contaduría pública',
        'licenciatura en lengua castellana y literatura',
        'comunicación social - periodismo',
        'gerontología',
        'licenciatura en educación comunitaria',
        'licenciatura en educación con énfasis en informática',
        'licenciatura en educación con énfasis en matemáticas',
        'licenciatura en educación infantil',
        'licenciatura en educación básica con énfasis en educación física, recreación y deportes',
        'licenciatura en educación física recreación y deportes',
        'licenciatura en humanidades y lengua castellana',
        'licenciatura en lenguas extranjeras: inglés-francés',
        'nutrición y dietética',
        'administración de empresas turísticas y hoteleras',
        'administración de la seguridad y salud en el trabajo',
        'administración pública',
        'gestión cultural y de industrias creativas',
        'licenciatura en etnoeducación e interculturalidad',
        'licenciatura en teología',
        'relaciones internacionales',
        'teología',
        'comunicación',
        'cultura física y deporte',
        'licenciatura en humanidades, lengua castellana e inglés',
        'comunicación y educación digital',
        'gobierno y relaciones internacionales',
        'licenciatura en lenguas extranjeras inglés',
        'licenciatura en tecnología e informática',
        'maestría en educación sostenible y gestión ambiental territorial',
        'profesional en innovación educativa',
        'profesional en lenguas extranjeras',
        'ciencia política y gobierno',
        'comercio internacional y finanzas',
        'publicidad',
        'comunicación social y periodismo',
        'comunicación corporativa',
        'economía y finanzas internacionales',
        'comunicación audiovisual y multimedios',
        'administración en logística y producción',
        'administración de negocios digitales',
        'administración en logística y producción',
        'administración de empresas agropecuarias',
        'artes liberales en ciencias sociales',
        'jurisprudencia',
        'periodismo y opinión pública',
        'pregrado en criminología e investigación criminal',
        'pregrado en emprendimiento',
        'mercadeo y negocios internacionales',
        'licenciatura en educación física',
        'licenciatura en educación física y deporte',
        'profesional en lengua inglesa',
        'profesional en teología',
        'licenciatura en teología',
        'administración en gestión documental y archivística',
        'licenciatura en educación básica primaria con énfasis en diversidad',
        'gerontología',
        'licenciatura en educación para la primera infancia',
        'licenciatura en educación religiosa',
        'nutrición y dietética',
        'comunicación social y periodismo digital',
        'licenciatura en bilingüismo con énfasis en inglés y español',
        'licenciatura en bilingüismo con énfasis en la enseñanza del inglés',
        'política y relaciones internacionales',
        'cultura física, deporte y recreación',
        'licenciatura en pedagogía infantil',
        'terapia respiratoria',
        'administración deportiva',
        'administración logística',
        'administración turística y hotelera',
        'gobierno y relaciones internacionales',
        'licenciatura en ciencias sociales',
        'licenciatura en lenguas extranjeras con énfasis en inglés - francés',
        'comunicación corporativa y relaciones públicas',
        'administración de empresas turísticas',
        'comunicación',
        'administración de empresas turísticas y hoteleras',
        'lenguas y cultura',
        'licenciatura en español y filología',
        'narrativa transmedia',
        'administración de negocios turísticos y hoteleros',
        'ciencia política, gobierno y relaciones internacionales',
        'profesional en danza teatro',
        'licenciatura en literatura y lengua castellana',
        'licenciatura en pedagogía infantil',
        'administración pública territorial',
        'administración policial',
        'planeación y desarrollo social',
        'actividad física y deporte',
        'ciencias del deporte y de la actividad física',
        'licenciatura en lenguas extranjeras con énfasis en inglés',
        'licenciatura en educación bilingüe',
        'licenciatura en lengua castellana',
        'administración hotelera y gastronómica',
        'profesional en entrenamiento deportivo',
        'psicología',
        'licenciatura en bilingüismo con énfasis en español e inglés',
        'administración de la calidad',
        'administración en servicios de salud',
        'comunicación política y gobierno',
        'profesional en deporte y actividad física',
        'profesional en lenguas',
        'profesional en mercadeo y publicidad',
        'profesional en negocios y logística internacional',
        'administración de mercadeo',
        'administración en salud',
        'comunicación social y medios digitales',
        'comunicación y periodismo',
        'ciencias del deporte y la actividad física',
        'licenciatura en lenguas extranjeras con énfasis en inglés',
        'licenciatura en inglés',
        'licenciatura en literatura y lengua castellana',
        'instrumentación quirúrgica',
        'comunicación social y periodismo',
        'administración comercial',
        'administración financiera y bursátil',
        'administración en seguridad alimentaria y nutricional',
        'administración en seguridad y salud en el trabajo',
        'ciencias bíblicas',
        'hotelería y turismo',
        'administración marítima y portuaria',
        'licenciatura en bilingüismo: español e inglés',
        'administración de empresas y finanzas',
        'profesional en cultura física y deporte',
        'administración comercial',
        'licenciatura en educación preescolar',
        'licenciatura en ciencias del deporte y la educación física',
        'profesional en turismo y gastronomía',
        'administración hotelera y de servicios',
        'administración comercial y de mercadeo',
        'administración de talento humano',
        'profesional en actividad física y deporte',
        'profesional en administración de empresas',
        'profesional en diseño de espacios',
        'hotelería y turismo',
        'publicidad digital y mercadeo',
        'gastronomía',
        'administración de empresas agroindustriales',
        'administración de la seguridad social',
        'administración de obras de arquitectura',
        'dirección y producción de medios audiovisuales',
        'administración integral de riesgos de seguridad y salud en el trabajo',
        'licenciatura en educación física, recreación y deporte',
        'profesional universitario en entrenamiento deportivo',
        'administración aeronáutica',
        'derecho',
        'educación física militar',
        'licenciatura en educación con enfasis en ciencias sociales',
        'licenciatura en pedagogia de la primera infancia',
        'licenciatura en bilingüismo con enfasis en ingles',
        'licenciatura en pedagogía de artes y saberes ancestrales',
        'licenciatura en pedagogía para la revitalización de lenguas originarias',
        'licenciatura en pedagogías comunitarias',
        'profesional en administración y gestión de la salud propia intercultural',
        'buen vivir comunitario',
        'comunicación propia intercultural',
        'derecho propio intercultural'
    ],
    emprendedor: [
        'mercadeo agroindustrial',
        'administracion de empresas agropecuarias',
        'administracion industrial',
        'administracion turistica y hotelera',
        'finanzas y comercio internacional',
        'administración financiera',
        'administración de empresas',
        'administración del turismo sostenible',
        'profesional en mercadeo',
        'administracion en finanzas y negocios internacionales',
        'administración de riesgos, seguridad y salud en el trabajo',
        'mercadeo',
        'comercio exterior',
        'administracion de negocios internacionales',
        'administración de empresas comerciales',
        'administración de empresas comerciales',
        'administracion de negocios internacionales',
        'finanzas y banca',
        'gestión del emprendimiento y la innovación',
        'administración de empresas',
        'gestión empresarial',
        'administración de empresas turísticas y hoteleras',
        'administración de servicios de salud',
        'administración de negocios',
        'negocios internacionales',
        'profesional en gastronomía',
        'administración deportiva',
        'administración marítima y portuaria',
        'administración pública',
        'finanzas',
        'administración de empresas agropecuarias',
        'mercadeo y publicidad',
        'negocios internacionales y mercadeo',
        'publicidad y marketing digital',
        'administración de mercadeo y logística internacionales',
        'mercadología',
        'administración de negocios digitales',
        'administración de mercadeo y logística internacionales',
        'esports management',
        'gestión y desarrollo urbanos',
        'marketing y negocios digitales',
        'pregrado en emprendimiento',
        'finanzas y negocios internacionales',
        'administración de negocios internacionales',
        'administración de empresas y transformación digital',
        'administración de negocios sostenibles',
        'administración de producción y logística internacional',
        'negocios digitales',
        'negocios, emprendimiento e innovación',
        'marketing integral y negocios globales',
        'marketing y transformación digital',
        'marketing & negocios internacionales',
        'administración de agronegocios',
        'archivística e inteligencia de negocios',
        'bibliotecología y estudios de la información',
        'negocios y relaciones internacionales',
        'negocios y finanzas internacionales',
        'formación de empresarios',
        'ingeniería comercial',
        'comunicación y relaciones corporativas',
        'marketing',
        'mercadeo internacional y publicidad',
        'administración de empresas',
        'administración',
        'contaduría pública y finanzas internacionales',
        'economía y negocios internacionales',
        'ingeniería empresarial',
        'mercadeo global',
        'administración ambiental y de los recursos naturales',
        'ingeniería comercial',
        'administración de empresas',
        'publicidad y mercadeo',
        'administración de empresas y gestión ambiental',
        'ingeniería financiera y de riesgo',
        'marketing digital',
        'marketing de negocios',
        'profesional en negocios internacionales',
        'administración y negocios internacionales',
        'administración financiera y de sistemas',
        'comercio y negocios internacionales',
        'comercio y negocios globales',
        'administración de empresas globales',
        'mercadeo digital',
        'mercadeo y ventas',
        'marketing y comunicación digital',
        'marketing digital y comunicación estratégica',
        'administración comercial',
        'administración de comercio exterior',
        'administración en salud y seguridad en el trabajo',
        'administración del deporte',
        'administración tecnológica',
        'administración de la cadena de suministro y logística',
        'comercio y finanzas internacionales',
        'profesional en mercadeo empresarial',
        'administración hotelera y de servicios',
        'administración de negocios internacionales',
        'administración comercial y de mercadeo',
        'administración agropecuaria',
        'administración de agronegocios',
        'administración de hotelería y turismo',
        'profesional en marketing y negocios digitales',
        'profesional en marketing internacional',
        'profesional en agroindustria',
        'administración comercial y de mercadeo',
        'administración de sistemas informáticos',
        'administración de la seguridad social',
        'administración de obras de arquitectura',
        'administracion',
        'administracion maritima',
        'administracion e innovación en turismo y hoteles',
        'administración aeronáutica',
        'mercadeo e innovación comercial',
        'logística y mercadeo organizacional',
        'administración de empresas turísticas y hoteleras',
        'administración y dirección de empresas',
        'administracion y gestión propia',
        'administración de empresas en telecomunicaciones',
        'marketing y publicidad',
        'publicidad y mercadeo digital'
    ],
    convencional: [
        'contaduría publica',
        'contaduría pública',
        'administración ambiental',
        'administración financiera',
        'ingenieria de software',
        'licenciatura en informática',
        'licenciatura en lenguas extranjeras con énfasis en inglés',
        'administración financiera',
        'licenciatura en informatica',
        'licenciatura en lenguas extranjeras con énfasis en inglés',
        'licenciatura en educación física, recreación y deportes',
        'licenciatura en educación física, recreacion y deportes',
        'licenciatura en español e inglés',
        'licenciatura en pedagogía de la madre tierra',
        'contaduría publica',
        'administracion de empresas comerciales',
        'comercio exterior',
        'contadur¿a publica',
        'gestión en ecología y turismo',
        'gestión territorial',
        'arquitectura',
        'contaduría pública',
        'administración de empresas turísticas y hoteleras',
        'administración de la seguridad y salud en el trabajo',
        'administración pública',
        'historia y archivística',
        'ciencia de la información, bibliotecología y archivística',
        'licenciatura en biología',
        'licenciatura en educación religiosa',
        'licenciatura en filosofía y letras',
        'licenciatura en lenguas extranjeras inglés',
        'licenciatura en tecnología e informática',
        'administración de empresas agropecuarias',
        'optometría',
        'banca y finanzas',
        'administración y servicio',
        'finanzas y relaciones internacionales',
        'economía y finanzas',
        'administración de negocios digitales',
        'administración en logística y producción',
        'administración de mercadeo y logística internacionales',
        'analítica de datos y mercados',
        'administración de empresas y transformación digital',
        'administración de empresas y transformación digital',
        'administración de empresas y transformación digital',
        'contaduría digital tech',
        'contaduría pública',
        'logística empresarial',
        'finanzas, fintech y comercio exterior',
        'finanzas, fintech y comercio exterior',
        'finanzas internacionales',
        'finanzas y comercio exterior',
        'administración de comercio internacional',
        'administración de negocios',
        'administración de producción y logística internacional',
        'administración de empresas agropecuarias',
        'contaduría internacional',
        'contaduría pública',
        'administración logística',
        'administración turística y hotelera',
        'contaduría pública y finanzas',
        'administración de empresas',
        'administración pública territorial',
        'profesional en seguridad y salud en el trabajo',
        'administración pública',
        'administración hotelera y gastronómica',
        'comunicación social - periodismo',
        'contaduría pública y finanzas internacionales',
        'administración de mercadeo',
        'administración humana',
        'profesional en gestión de la seguridad y la salud laboral',
        'licenciatura en matemáticas y computación',
        'ingeniería administrativa',
        'mercadeo y estrategia comercial',
        'pregrado en administración en salud',
        'turismo sostenible',
        'administración en tecnologías de la información',
        'administración en seguridad y salud en el trabajo',
        'administración en salud',
        'administración de empresas',
        'administración comercial',
        'profesional en criminalística',
        'profesional en gestión de la seguridad y salud en el trabajo',
        'administración en salud y seguridad en el trabajo',
        'administración de sistemas informáticos',
        'administración agropecuaria',
        'administración de la cadena de suministro y logística',
        'comercio y finanzas internacionales',
        'profesional en mercadeo empresarial',
        'profesional en marketing y negocios digitales',
        'administración de talento humano',
        'administración agropecuaria',
        'profesional en diseño visual digital',
        'ingeniería de procesos industriales',
        'administración de agronegocios',
        'profesional en administración de empresas',
        'profesional en contaduría pública',
        'administración de seguridad y salud en el trabajo',
        'administración en seguridad y salud en el trabajo',
        'administración empresarial',
        'administracion de empresas turísticas y hoteleras',
        'administración aeronáutica',
        'administración de la seguridad y salud en el trabajo',
        'contaduría pública',
        'profesional en administración en seguridad y salud en el trabajo',
        'administracion de sistemas',
        'administración y gestión propia',
        'administración de empresas en telecomunicaciones'
    ]
}
